# Generated by Django 2.2.6 on 2020-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200418_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(2, 2), (1, 1), (0, 0)], default=0),
        ),
    ]
